---
title: "Strobmers' Evaluation"
#output:
#  pdf_document: default
#  html_notebook: default
path_kmer_file: "`r path_kmer_file`"
path_output_file: "`r path_output_file`"
---

```{r}
build_random_seeds <- function(strobmers_data, header_data, type_kmer)
{
  w_min <- header_data$w_min
  w_max <- header_data$w_max
  vec_rand_seeds <- c()
  for(i in 1:header_data$NumberofSeeds)
  {
    rand <- sample(1:(w_max - w_min + 1), 1)
    new_elem <- w_min + i + rand - 1

    ##
    ##print(c(i, new_elem));
    ##write(c(i, new_elem),file="res.txt",append=TRUE)
    ##
  
    if(type_kmer == 3)
    {
      rand2 <- sample(1:(w_max - w_min + 1), 1)
      new_elem <- w_min + new_elem + rand2 - 1
    }
    vec_rand_seeds <- append(vec_rand_seeds, new_elem)
  }
  return(vec_rand_seeds)
}
```

```{r}
calculate_ks_test_k2 <- function(strobmbers_data, header_data, type_kmer)
{
  rand_seeds <- build_random_seeds(strobmers_data, header_data, type_kmer)
  if(type_kmer == 2)
  {
    p_val_diff <- ks.test(rand_seeds, strobmbers_data$kmer_2)
  }else
  {
     p_val_diff <- ks.test(rand_seeds, strobmbers_data$kmer_3)
  }
  return(p_val_diff$p.value)
}
```

```{r}
calculate_ks_test_diff <- function(strobmbers_data, header_data, type_kmer)
{
  rand_seeds <- build_random_seeds(strobmers_data, header_data, type_kmer)
  if(type_kmer == 2)
  {
    diff_base_strobe <- strobmbers_data$kmer_2 - strobmers_data$kmer_1
  }
  else
  {
    diff_base_strobe <- strobmbers_data$kmer_3 - strobmers_data$kmer_2
  }
  diff_rand <- rand_seeds - 1:nrow(strobmers_data)
  p_val_diff <- ks.test(diff_base_strobe, diff_rand)
  return(p_val_diff$p.value)
}
```


```{r}
calculate_unique_hashes <- function(strobmers_data, type_kmer)
{
  if(type_kmer == 2)
  {
    hash_df <- strobmers_data[, c("hash_1", "hash_2")]
    hash_df <- unique(hash_df)
  }
  else 
  {
    hash_df <- strobmers_data[, c("hash_1", "hash_2", "hash_3")]
    hash_df <- unique(hash_df)
  }
  return(nrow(hash_df))
}
```


```{r}
calculate_unique_k2 <- function(strobmers_data, type_kmer)
{
  if(type_kmer == 2)
  {
    table_kmer2 <- table(strobmers_data$kmer_2)
  }
  else
  {
      table_kmer2 <- table(strobmers_data$kmer_3)
  }
  return(length(names(table_kmer2)))
}
```

```{r}
calculate_ehits <- function(strobmers_data, type_kmer)
{
  if(type_kmer == 2)
  {
   table_kmer2 <- table(strobmers_data$kmer_2)
  }
  else 
  {
    table_kmer2 <- table(strobmers_data$kmer_3)
  }
  count_vector <- as.vector(table_kmer2)
  count_vector <- count_vector ^ 2;
  return(mean(count_vector))
  #print(paste("The E-hits metric value is: ", mean(count_vector)))
}
```

```{r}
calculate_ehits_diff <- function(strobmers_data, type_kmer)
{
  if(type_kmer == 2)
  {
    diff_vec <- strobmers_data$kmer_2 - strobmers_data$kmer_1
  }
  else 
  {
    diff_vec <- strobmers_data$kmer_3 - strobmers_data$kmer_2
  }
  table_diff <- table(diff_vec)
  print(table_diff)
  vec_table_dif <- as.vector(table_diff)
  vec_table_dif <- vec_table_dif ^ 2
  return(mean(vec_table_dif))
}
```

```{r}
evaluate_sample <- function(strobmers_data, header_data, output_evaluation, type_kmer)
{
   if(header_data$Sample == 1)
   {
    hist(strobmers_data$kmer_2, xlab = "Second Kmer Position", main = "Histogram Second Kmer", ylab = "Count", 
         breaks = 1000)
   }
   if(type_kmer == 2)
   {
     time_execution <- header_data$TimeExecution
     ehits <- calculate_ehits(strobmers_data, 2)
     unique_k2 <- calculate_unique_k2(strobmers_data, 2)
     unique_hashes <- calculate_unique_hashes(strobmers_data, 2)
     p_val_diff <- calculate_ks_test_diff(strobmers_data, header_data, 2)
     p_val_kmer2 <- calculate_ks_test_k2(strobmers_data, header_data, 2)
     diff_ehits <- calculate_ehits_diff(strobmers_data, 2)
     hash_method <- as.character(header_data$HashMethod)
     randstrobe_method <- as.character(header_data$SeedGeneratorMethod)
    # conflict <- calculate_conflict_metric(strobmers_data, header_data)

  
     output_evaluation[nrow(output_evaluation) + 1,] <- list(time_execution, ehits, diff_ehits, unique_k2, unique_hashes,
                                                          p_val_diff, p_val_kmer2, 
                                                          hash_method, randstrobe_method, header_data$Sample)
   }else 
   {
     time_execution <- header_data$TimeExecution
     ehits2 <- calculate_ehits(strobmers_data, 2)
     ehits3 <- calculate_ehits(strobmers_data, 3)
     unique_k2 <- calculate_unique_k2(strobmers_data, 2)
     unique_k3 <- calculate_unique_k2(strobmers_data, 3)
     unique_hashes <- calculate_unique_hashes(strobmers_data, 3)
     p_val_diff2 <- calculate_ks_test_diff(strobmers_data, header_data, 2)
     p_val_diff3 <- calculate_ks_test_diff(strobmers_data, header_data, 3)
     p_val_kmer2 <- calculate_ks_test_k2(strobmers_data, header_data, 2)
     p_val_kmer3 <- calculate_ks_test_k2(strobmers_data, header_data, 3)
     diff_ehits2 <- calculate_ehits_diff(strobmers_data, 2)
     diff_ehits3 <- calculate_ehits_diff(strobmers_data, 3)
     hash_method <- as.character(header_data$HashMethod)
     randstrobe_method <- as.character(header_data$SeedGeneratorMethod)
   #  conflict <- calculate_conflict_metric(strobmers_data, header_data)
  
     output_evaluation[nrow(output_evaluation) + 1,] <- list(time_execution, ehits2, ehits3, 
                                                          diff_ehits2, diff_ehits3, unique_k2, unique_k3, 
                                                          unique_hashes, p_val_diff2, p_val_diff3,
                                                          p_val_kmer2, p_val_kmer3,
                                                          hash_method, randstrobe_method, header_data$Sample)
   }
   return(output_evaluation)
}
```


```{r read_arg, include=FALSE}
## path_kmer_file <- readline(prompt = "Please Enter kmers file path for evaluation: ")

path_header_file <- path_kmer_file
path_kmer_file <- paste("../BenchMarkResults/Results/", path_kmer_file, sep = "")
path_header_file <- paste("../BenchMarkResults/Headers/", path_header_file, sep = "")

#Reading csv files

strobmers_data <- read.csv(path_kmer_file)
header_data <- read.csv(path_header_file)

#Constructing a dataframe for output

kmer_type = header_data$n[1]

if(kmer_type == 2)
{
  columns = c("TimeofExecution","E-hits_metric","E-hits-diff", "UniqueKmers_2", "UniqueHashes", "KS-test-diff",                                   "KS-test-kmer2","HashMethod", 
                "RandStrobeMethod", "Sample") 
}else 
{
    columns = c("TimeofExecution","E-hits_metric_kmer2", "E-hits_metric_kmer3",
                "Diff-E-hits-kmer2", "Diff-E-hits-kmer3",
                "UniqueKmers_2", "UniqueKmers_3", "UniqueHashes", "KS-test-diff_kmer2",
                "KS-test-diff_kmer3", "KS-test-kmer2", "KS-test-kmer3", "HashMethod", 
                "RandStrobeMethod", "Sample") 
}
output_evaluation = data.frame(matrix(nrow = 0, ncol = length(columns))) 
colnames(output_evaluation) = columns
output_median <- output_evaluation

#path_output_file <- readline(prompt = "Please Enter output file path for results: ")

path_output_all_samples <- paste("../EvaluationResults/AllSamples/", path_output_file, sep = "")
path_output_median_samples <- paste("../EvaluationResults/MedianSamples/", path_output_file, sep = "")

#Evaluation 

for(i in 1:nrow(header_data))
{
  #header_data
  #header_data[header_data['Sample']== 1, ]
  output_evaluation <- evaluate_sample(strobmers_data[strobmers_data['Sample'] == i, ], 
                                       header_data[i, ], output_evaluation,
                                       kmer_type)
}

  write.csv(output_evaluation, path_output_all_samples, row.names = FALSE)
  deleted <- c('Sample', 'HashMethod', 'RandStrobeMethod')
  output_median <- data.frame(HashMethod = output_evaluation$HashMethod[1], RandStrobeMethod =                                                            output_evaluation$RandStrobeMethod[1])
  for(i in 1:ncol(output_evaluation))
  {
    if(names(output_evaluation)[i] %in% deleted)
    {
      next
    }
    output_median[, names(output_evaluation)[i]] = median(output_evaluation[, i])
  }
  #median_output <- apply(new_data, 2, median)
  #median_output <- as.vector(median_output)
  #output_median[1, ] <- median_output
  #print(output_median)
  write.csv(output_median, path_output_median_samples, row.names = FALSE)


```


