---
title: "R Notebook"
output: html_notebook
---


```{r}
create_name_file <- function(name_now)
{
  name_now <- gsub("kmer", "strobe", name_now)
  name_now <- gsub("E.hits", "E-hits", name_now)
  name_now <- gsub("\\.", " ", name_now)
  name_now <- gsub("postion", "position", name_now)
  name_now <- gsub("E-hits position distance between strobe2 and strobe1", "E-hits distance between strobe2 and strobe1", name_now)
  name_now <- gsub("E-hits position distance between strobe3 and strobe1", "E-hits distance between strobe3 and strobe1", name_now)
  name_now <- gsub("E-hits position distance between strobe3 and strobe2", "E-hits distance between strobe3 and strobe2", name_now)
    name_now <- gsub("TimeofExecution", "Time of execution", name_now)
    return(name_now)
}
```

```{r}
create_rand_strobe_methods <- function(rand_strobe_now)
{
  rand_ans <- c()
  for(str in rand_strobe_now)
  {
    if(str == "XOR")
    {
      rand_ans <- append(rand_ans, TeX(r"($\u2113_{XOR}$)"))
    }
    else 
      rand_ans <- append(rand_ans, str)
  }
  return(rand_ans)
}
```

```{r}
to_latex <- function(input_str)
     TeX(paste("$", input_str, "$"))

```

```{r}
draw_normalized_plot <- function(data_all_methods, new_data, name_now, i)
{
  plot_now <- ggplot(data_all_methods,
         aes(fill = HashMethod , y = new_data[, i], x = RandStrobeMethod)
         ) + geom_bar(position="dodge", stat="identity") +  theme(title = element_text(size = 120), 
                                                                  
                                                                  plot.title = element_text( margin = margin(t = 120, b = 120)),
                                                                  axis.title=element_text(size = 140),
                                                                  axis.title.x = element_text(size = 140, margin = margin(300, 300, 300, 300)),
                                                                                                                                                                                                           axis.title.y = element_text(size = 140, margin = margin(360, 360, 360, 360)),

                                                                  legend.text = element_text(size = 140),
                                                                  legend.title = element_text(size = 140),
                                                                  axis.text = element_text(size = 120),
                                                                  axis.text.x = element_text(margin = margin(100, 100, 100, 100)),
                                                                 legend.margin = margin(60, 60, 60, 60)) + 
    guides(fill=guide_legend(title="Hashes")) + scale_fill_discrete(labels = to_latex) + scale_x_discrete(labels = to_latex) +
theme(legend.text.align = 0) +   facet_wrap(~Comperator, ncol=1) + theme(plot.margin = unit(c(60,60,60,60), "lines"), strip.text = element_text(size = 140)) + 
  theme(legend.text.align = 0) + coord_cartesian(ylim = c(min(new_data[, i]), NA))
   plot_now <- plot_now + labs(title = paste(name_now, added_str),
              x = "RandStrobe Method", y =  name_now)
  png(filename=paste("../EvaluationResults/Figures/", paste("Normalized", name_now), ".png",sep = ""), width=8000, height= 8000)
  print(plot_now)
  dev.off()
  ggsave( filename = paste("../EvaluationResults/Figures/", name_now, ".pdf",sep = ""), 
    plot = plot_now, width = 45, height = 30
  )
}
```



```{r}
library(ggplot2)
library(latex2exp)
#library(cowplot)

all_files <- list.files(path = "../EvaluationResults/MedianSamples")
cnt <- 1
for(file_now in all_files)
{
  print(file_now)
  path_now = paste("../EvaluationResults/MedianSamples/", file_now, sep = "")
  print(path_now)
  new_csv <- read.csv(path_now)
  print(ncol(new_csv))
  if(cnt == 1)
  {
    data_all_methods <- new_csv
  }else
  {
    data_all_methods <- rbind(data_all_methods, new_csv)
  }
  cnt <- cnt + 1
  print(cnt)
}

data_all_methods <- data_all_methods[!grepl('FixedSahlinMod', data_all_methods$RandStrobeMethod),]
data_all_methods <- data_all_methods[!grepl('MAXor', data_all_methods$RandStrobeMethod),]
data_all_methods <- data_all_methods[!grepl('MAXorVar', data_all_methods$RandStrobeMethod),]
data_all_methods <- data_all_methods[!grepl('RandomMAMod', data_all_methods$RandStrobeMethod),]
data_all_methods <- data_all_methods[!grepl('SpecialCaseFixedShen', data_all_methods$RandStrobeMethod),]



levels(data_all_methods$HashMethod) <- c(levels(data_all_methods$HashMethod), "None")
data_all_methods$HashMethod[data_all_methods$HashMethod == "NoHash"] <- "None"
#levels(data_all_methods$HashMethod) <- c(levels(data_all_methods$HashMethod), "None-min")
#data_all_methods$HashMethod[data_all_methods$HashMethod == "NoHash-min"] <- "None-min"
levels(data_all_methods$HashMethod) <- c(levels(data_all_methods$HashMethod), "TW")
data_all_methods$HashMethod[data_all_methods$HashMethod == "ThomasWangHash"] <- "TW"
#levels(data_all_methods$HashMethod) <- c(levels(data_all_methods$HashMethod), "TW-min")
#data_all_methods$HashMethod[data_all_methods$HashMethod == "ThomasWangHash-min"] <- "TW-min"
levels(data_all_methods$HashMethod) <- c(levels(data_all_methods$HashMethod), "Wy")
data_all_methods$HashMethod[data_all_methods$HashMethod == "WyHash"] <- "WY"
#levels(data_all_methods$HashMethod) <- c(levels(data_all_methods$HashMethod), "Wy-min")
#data_all_methods$HashMethod[data_all_methods$HashMethod == "WyHash-min"] <- "WY-min"
levels(data_all_methods$HashMethod) <- c(levels(data_all_methods$HashMethod), "XX")
data_all_methods$HashMethod[data_all_methods$HashMethod == "XXHash"] <- "XX"
#levels(data_all_methods$HashMethod) <- c(levels(data_all_methods$HashMethod), "XX-min")
#data_all_methods$HashMethod[data_all_methods$HashMethod == "XXHash-min"] <- "XX-min"

levels(data_all_methods$RandStrobeMethod) <- c(levels(data_all_methods$RandStrobeMethod), "XOR")
data_all_methods$RandStrobeMethod[data_all_methods$RandStrobeMethod == "GuoPibri"] <- "\u2113_{XOR}"

levels(data_all_methods$RandStrobeMethod) <- c(levels(data_all_methods$RandStrobeMethod), 'MOD')
data_all_methods$RandStrobeMethod[data_all_methods$RandStrobeMethod == "SahlinMod"] <- '\u2113_{MOD}'

levels(data_all_methods$RandStrobeMethod) <- c(levels(data_all_methods$RandStrobeMethod), "AND")
data_all_methods$RandStrobeMethod[data_all_methods$RandStrobeMethod == "Shen"] <- "\u2113_{AND}"

levels(data_all_methods$RandStrobeMethod) <- c(levels(data_all_methods$RandStrobeMethod), "BC")
data_all_methods$RandStrobeMethod[data_all_methods$RandStrobeMethod == "SahlinBitCount"] <- "\u2113_{BC}"

levels(data_all_methods$RandStrobeMethod) <- c(levels(data_all_methods$RandStrobeMethod), "CC")
data_all_methods$RandStrobeMethod[data_all_methods$RandStrobeMethod == "LiuPatroLi"] <- "\u2113_{CC}"

levels(data_all_methods$RandStrobeMethod) <- c(levels(data_all_methods$RandStrobeMethod), "XV")
data_all_methods$RandStrobeMethod[data_all_methods$RandStrobeMethod == "XorVar"] <- "\u2113_{XV}"

levels(data_all_methods$RandStrobeMethod) <- c(levels(data_all_methods$RandStrobeMethod), "MAMD")
data_all_methods$RandStrobeMethod[data_all_methods$RandStrobeMethod == "MAMod"] <- "\u2113_{MAMD}"

data_all_methods2 <- data_all_methods[!grepl('Uniform', data_all_methods$RandStrobeMethod),]

deleted <- c('HashMethod', 'RandStrobeMethod', 'Comperator')
new_data <- data_all_methods
new_data2 <- data_all_methods2
new_data$Sample <- NULL
new_data$RandStrobeMethod <- NULL
new_data$HashMethod <- NULL
new_data2$Sample <- NULL
new_data$Comperator <- NULL
new_data2$RandStrobeMethod <- NULL
new_data2$HashMethod <- NULL
new_data2$Comperator <- NULL
for(i in 1:ncol(new_data))
{
  temp <- data_all_methods
  temp2 <- new_data
  #print(data_all_methods$Comperator)
  print(names(new_data)[i])
        if(names(new_data)[i] == "TimeofExecution" || names(new_data)[i] == "Number.of.unique.Strobmers" ||
     names(new_data)[i] == "Number.of.unique.final.seed.hash.values"||
     names(new_data)[i] == "Ratio.of.number.of.unique.final.seed.hash.value.to.number.of.unique.strobmers" ||   names(new_data)[i] == "E.hits.of.Strobmers" ||  names(new_data)[i] == "E.hits.of.final.seed.hash.values")
  {
    data_all_methods <- data_all_methods2
    new_data <- new_data2
  }
  col_now <- data_all_methods[, names(new_data)[i]]
  sorted_data <- data_all_methods[order(col_now), ]
  file_name <- paste("../EvaluationResults/MetricsSortedByMethods/", names(new_data)[i], ".csv",sep = "")
  sorted_data <- sorted_data[, c('HashMethod', 'RandStrobeMethod', names(new_data)[i])]
  
  rand_strobe_method <- create_rand_strobe_methods(data_all_methods$RandStrobeMethod)

  write.csv(sorted_data, file_name, row.names = FALSE)
  normalized_by = min(new_data[ , i])
  new_data_normalized <- new_data
  new_data_normalized[, i] <- new_data_normalized[, i] - normalized_by
#  if(names(new_data)[i] != "TimeofExecution" && names(new_data)[i] != "Number.of.unique.Strobmers" &&
#     names(new_data)[i] != "Number.of.unique.final.seed.hash.values" &&
#     names(new_data)[i] != "Ratio.of.number.of.unique.final.seed.hash.value.to.number.of.unique.strobmers" &&   names(new_data)[i] != "E.hits.of.Strobmers" &&  names(new_data)[i] != "E.hits.of.final.seed.hash.values")
  #{
  #    new_data[, i] <- new_data[, i] / normalized_by
  #}
  #print(names(new_data)[i])
  layout(matrix(c(1,2), nrow = 1))
  plot_now <- ggplot(data_all_methods,
         aes(fill =  HashMethod, y = new_data[, i], x = RandStrobeMethod)
         ) + geom_bar(position="dodge", stat="identity") + theme(title = element_text(size = 120), 
                                                                  
                                                                  plot.title = element_text( margin = margin(t = 120, b = 120)),
                                                                  axis.title=element_text(size = 140),
                                                                  axis.title.x = element_text(size = 140, margin = margin(300, 300, 300, 300)),
                                                                                                                                                                                                           axis.title.y = element_text(size = 140, margin = margin(360, 360, 360, 360)),
                                                                  axis.text.x = element_text(margin = margin(100, 100, 100, 100)),

                                                                  legend.text = element_text(size = 140),
                                                                  legend.title = element_text(size = 140),
                                                                  axis.text = element_text(size = 120, margin = margin(t = 60, b = 60)),
                                                                 legend.margin = margin(60, 60, 60, 60)) + 
    guides(fill=guide_legend(title="Hashes")) + scale_fill_discrete(labels = to_latex) + scale_x_discrete(labels = to_latex) +
theme(legend.text.align = 0) +   facet_wrap(~Comperator, ncol=1) + theme(plot.margin = unit(c(60,60,60,60), "lines"), strip.text = element_text(size = 140))
  
  added_str <- ""
 # added_str <- "based on hashes and linkings"
 #   if(names(new_data)[i] == "E.hits.Unique.Strobmers" || names(new_data)[i]  == "Unique.Strobmers" || names(new_data)[i] == "E.hits.Unique.Strobmers")
#    added_str <- "based on final seed hash values"
  
  
  name_now <- names(new_data)[i]
  name_now <- create_name_file(name_now)

 # if(names(new_data)[i] != "TimeofExecution" && names(new_data)[i] != "Number.of.unique.Strobmers" &&
 #    names(new_data)[i] != "Number.of.unique.final.seed.hash.values" &&
 #    names(new_data)[i] != "Ratio.of.number.of.unique.final.seed.hash.value.to.number.of.unique.strobmers" &&   names(new_data)[i] != "E.hits.of.Strobmers" &&  names(new_data)[i] != "E.hits.of.final.seed.hash.values")
 #   plot_now <- plot_now + labs(title = paste(name_now, added_str),
  #            x = "Hashes", y =  paste("Normalized ", name_now, sep = ""))
  #else 
      plot_now <- plot_now + labs(title = paste(name_now, added_str),
              x = "RandStrobes Method", y =  name_now)
  
  png(filename=paste("../EvaluationResults/Figures/", name_now, ".png",sep = ""), width=8000, height= 8000)
  print(plot_now)
  dev.off()
  ggsave( filename = paste("../EvaluationResults/Figures/", name_now, ".pdf",sep = ""), 
          plot = plot_now, width = 45, height = 30
)

  draw_normalized_plot(data_all_methods, new_data, name_now, i)
  data_all_methods <- temp
  new_data <- temp2
}
  #row.names(data_all_methods) <- data_all_methods$RandStrobeMethod
#print(data_all_methods)
```
